### ISSUE TITLE
ntfs.gatherAllFiles no output

### ISSUE THREAD

**Issue by pandatest2023** [DougRogers/NTFSDirectorySystem#2]
Hello, I want to get a list of all files on the drive. What should I do?

I tried before ntfs.gatherAllFiles,But failed
no output

**Comment by pandatest2023** [comment]
I'm a novice, I can't solve it, help me

**Comment by DougRogers** [comment]
You have to be in admin mode.

**Comment by pandatest2023** [comment]
> You have to be in admin mode.

I test  in the virtual machine , no output (administrator & system permissions)

I printed the _loadMFT function variable disk->type and found that it is not equal to eNTFS_DISK //(1)

output : disk->type =  -6684775

driveMask = DISK_C;

windows 7 x64  fail

![image](https://user-images.githubusercontent.com/12782343/101999262-428c5500-3d16-11eb-8e29-5297461b9ab8.png)


 windows 10 sucess
![image](https://user-images.githubusercontent.com/12782343/101999241-0527c780-3d16-11eb-94af-582c34b58931.png)
