### ISSUE TITLE
how to get file size and time?

### ISSUE THREAD

**Issue by pkuntik** [DougRogers/NTFSDirectorySystem#3]
i try to get them,but it is not right.

**Comment by DougRogers** [comment]
For file size:
https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfilesize

for time:
https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfiletime

Example:
https://docs.microsoft.com/en-us/windows/win32/sysinfo/retrieving-the-last-write-time
